sudo: false

language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - asciidoc
    - jpegoptim
    - libfreetype6-dev
    - libjpeg-progs
    - libjpeg8-dev
    - liblcms2-dev
    - libpcre3-dev
    - libtiff4-dev
    - libwebp-dev
    - libxml2-dev
    - libxslt1-dev
    - nodejs
    - optipng
    - python-tk
    - tcl8.5-dev
    - tk8.5-dev
    - zlib1g-dev

# Cache pip requirements for faster builds
cache:
  directories:
    - $HOME/.cache/pip

install:
  # JS dependencies
  - npm install sass@0.5.0 requirejs@2.1 stylus@0.51 uglify-js@2.4.23 less@2.5.1

  # Python test requirements
  - pip install tox

# Run each tox environment separately
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pep8
  - TOX_ENV=docs

before_script:
  - export PATH=$(pwd)/node_modules/.bin:$PATH
  - export PYTHONPATH=$PYTHONPATH:/usr/share/asciidoc/

script:
  - tox -e $TOX_ENV

# Only build for the master branch
# Note that this does not prevent pull request builds
branches:
  only:
    master

notifications:
  irc:
    channels: chat.freenode.net#hyde
